complete Desktop view
saied2035/mobile-version-skeleton pull request #6
Opened 2022-01-12 20:02 UTC by saied2035

## **In** this branch I made the desktop version of the project and made it resopnsive to the desktop&mobile

2022-01-12 21:09 UTC, mmsesay requested changes
Hi @saied2035 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-12 21:09 UTC, mmsesay commented on index.css
> +@media only screen and (min-width: 800px) {
- [x] You did well setting the media query for your website. However, this min-width value `800px` is a bit smaller. For your website to be responsive on other screens, I will suggest you increase the min-width value to `992px`.

2022-01-12 21:09 UTC, mmsesay commented on index.html
> +    	   <button type="button" id="About-button">Get My Resume</button>
- [x] I think that the about section contents are well placed. But I found out that your design has a large space between the `p` tag and the `button`. I believe you can fix that. Try checking if you apply some padding in that section. 

Your Design | Figma Design |
:---------------:|:-------------------:|
![e1](https://user-images.githubusercontent.com/39523312/149220062-11e3218e-4c80-48d6-8ef1-1974768a252f.png) |![e3](https://user-images.githubusercontent.com/39523312/149220072-b16d7b00-8988-44ff-a803-e5c830df5895.png)

2022-01-12 21:09 UTC, mmsesay commented on index.html
> +    	   <div class="categories">
- [ ] These section contents are well placed. But I found out that your design has a smaller space between the ending cards and the contact form section. I believe you can fix that by adding the spacing to match with the Figma design.
Also, take note of the input focus colours.

Your Design | 
:---------------:|
 ![e2](https://user-images.githubusercontent.com/39523312/149220678-d2d6be7f-6130-42fd-9314-153dc9a86517.png)

Figma Design |
:------------------:|
![e4](https://user-images.githubusercontent.com/39523312/149220683-475fae0f-4775-4e87-9c11-e53979f44e8f.png)

2022-01-13 08:11 UTC, brytebee approved these changes
Hi @saied2035👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-13 08:28 UTC, merged

2022-01-17 08:47 UTC, micheaol reviewed
Hi @saied2035 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, with a closed Pull request.

Please ensure that you open a new pull request with the branch that has a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section')

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._